name: ci

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - master
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master

jobs:

  test:
    # NOTE: This name appears in GitHub's Checks API.
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint code
        run: |
          flake8 suffix_trees/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --show-source
        # Always run this step so that all linting errors can be seen at once.
        if: always()
      - name: Run tests
        run: |
          pytest --cov=suffix_trees/
        # Always run this step so that all linting errors can be seen at once.
        if: always()
      - name: Generate and run test vectors
        # TODO: could cache the gen_vectors.py result.
        run: |
          python3 suffix_trees/test/gen_vectors.py
          SUFFIX_TREES_TEST_VECTORS=1 pytest --cov=suffix_trees/ --cov-append suffix_trees/test/test_vectors.py
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
        # Only run matrix if previous jobs are succesful and with Python version 3.8.
        if: success() && matrix.python-version == 3.8
